BASE_URL = "https://www.tiktok.com"

BLOCKED_RESOURCE_TYPES = {"font"}

BROWSER_PREFERENCE = ("chromium", "firefox")
STORAGE_STATE_PATH = ".playwright/tiktok_state.json"

WORKERS = 5
MAX_RETRY_ATTEMPTS = 3
GRID_RECOVERY_ATTEMPTS = 3

TIMEOUT_PAGE_LOAD = 20000
TIMEOUT_POST_LOAD = 15000
TIMEOUT_PROFILE_READY = 15000
TIMEOUT_FIRST_POST_READY = 18000
TIMEOUT_POST_READY = 8000
TIMEOUT_GRID_RECOVERY = 8000
TIMEOUT_POPUP_DISMISS = 3000
TIMEOUT_SCROLL = 5000

USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)
VIEWPORT = {"width": 1280, "height": 900}
LOCALE = "en-US"
TIMEZONE_ID = "Europe/Paris"
EXTRA_HTTP_HEADERS = {
    "Accept-Language": "en-US,en;q=0.9,fr;q=0.8",
}

POPUP_DISMISS_WAIT = 1.0
SCROLL_POLL_INTERVAL = 0.3
RESPONSE_HANDLER_WAIT = 1.0
FIRST_POST_EXTRA_WAIT = 2.0
VIDEO_RETRY_BACKOFF = 1.2
HUMAN_DELAY_MIN = 0.35
HUMAN_DELAY_MAX = 1.15
HUMAN_LONG_DELAY_MIN = 1.2
HUMAN_LONG_DELAY_MAX = 2.4
